version: '3.8'

services:
  # Nginx 
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx/default.template:/etc/nginx/conf.d/default.template:ro
    command: /bin/sh -c "envsubst '$$PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - PORT=${PORT}
    depends_on:
      - app

  # App
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: microservice_product_categories_app
    env_file:
      - .env
    environment:
      - MONGODB_CNN=mongodb://mongodb:27017/${MONGO_DATABASE}
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "npm", "start"]
    volumes:
      - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh:ro
    depends_on:
      - mongodb

  # MongoDB
  mongodb:
    image: mongo:6.0.1
    container_name: mongodb_container
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
